name: Cypress tests
on:
    pull_request:
        branches:
            - '*'
jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'yarn'

            - name: Lint checking
            - run: yarn lint

            - name: Install dependecies
              run: yarn

            - name: 'Create .env.local file'
              run: |
                echo "${{ secrets.ENV_LOCAL }}" > .env.local

            - name: Start server
              run: yarn dev &

            - name: Install Cypress and run tests
              uses: cypress-io/github-action@v5
